### PR TITLE
Add null safety support

### LINKED ISSUE #31: Migrate to sound null safety
### **Description**

- Migrate to sound null safety
- Bump up package version

### PR DESCRIPTION
**Pull request by areille**
This PR closes #31 .

I followed the steps mentioned on [this page](https://dart.dev/null-safety/migration-guide).

Some points to mention :
- `Widget`-returning functions which returned `null` now return `const SizedBox()`, which is an empty `Widget`
- as tere is not many tests for this plugin, we could use some more manual testing

### CODE REVIEW

**Review by KabinManandhar — APPROVED** [review]

**Review by KabinManandhar — DISMISSED** [review]

**Comment by areille** [comment]
Last example demo does not work, will have a look at it.

**Comment by areille** [comment]
@KabinManandhar this should be ok now ! 👍

**Comment by vjrj** [comment]
Thanks @areille ! The `ProcessTimelinePage` of the examples does not work well:

2021-11-19-23-28-52-screenshot

I tried to find the bug today without success.

**Comment by chulwoo-park** [comment]
Sorry I'm toooooo late.

I haven't been paying attention.
I'll review it over the weekend and distribute it right away if there is no problem!

THX!

**Comment by chulwoo-park** [comment]
@areille
Thank you so much for working on it.

I was revert this changes(please check once for anything missing):
> - `Widget`-returning functions which returned `null` now return `const SizedBox()`, which is an empty `Widget`

because connectors is positioned by null checkes in timeline tile builder.

@vjrj 
Please check the bug in 6d4cf0e. It was fine when I tried it.

**Review by chulwoo-park — DISMISSED** [review]

**Comment by vjrj** [comment]
@chulwoo-park yes, work now for me. Thanks indeed for both of you

**Pull request merged**
